In [1]:
import numpy as np
import pandas as pd
import os, glob
pd.options.display.float_format = '{:0.4f}'.format

In [6]:
df = pd.read_csv('/MFMDatasets/MFM_bopf/data/csl/CSL_he_PI_comp.csv', header=0, index_col=0)
df

In [8]:
df

high_EBL  Accrete  AdmBishop  Admcervpos  Admconsistency  \
MomID                                                                
41-00003         0        0          6           3               2   
41-00004         0        0          5           3               2   
41-00006         0        0         11           1               3   
41-00007         0        0          4           2               2   
41-00008         0        0          6           3               2   
...            ...      ...        ...         ...             ...   
52-07247         0        0          8           8               8   
52-07248         0        0          8           8               8   
52-07249         1        0          8           8               8   
52-07250         0        0          8           8               8   
52-07251         0        0          8           8               8   

          Admcontract  AdmDBP  Admefface  Admpresent   AdmSBP  ...  \
MomID                                                          ...   
41-00003       2.9000      77    70.0000           1 105.0000  ...   
41-00004       3.3000      65    70.0000           1 122.0000  ...   
41-00006       5.0000      98   100.0000          77 134.0000  ...   
41-00007       2.9000     105    50.0000          77 145.0000  ...   
41-00008       6.7000      71    70.0000          77 118.0000  ...   
...               ...     ...        ...         ...      ...  ...   
52-07247      77.0000      74    70.0000           1 124.4000  ...   
52-07248      99.0000      74     0.0000           2 124.4000  ...   
52-07249      66.0000      74     0.0000          77 124.4000  ...   
52-07250      66.0000      74    90.0000           1 124.4000  ...   
52-07251      66.0000      74   100.0000           1 124.4000  ...   

          ThreatenedPB  threatpb9  UnspecHBP  uscar  version9  new_age  \
MomID                                                                    
41-00003             0          0          0      0         0       36   
41-00004             0          0          0      0         0       34   
41-00006             0          0          0      0         0       21   
41-00007             0          0          0      0         0       42   
41-00008             0          0          0      0         0       33   
...                ...        ...        ...    ...       ...      ...   
52-07247             0          0          0      0         0       19   
52-07248             0          0          0      1         0       34   
52-07249             0          0          0      1         0       28   
52-07250             0          0          0      0         0       16   
52-07251             0          0          0      0         0       44   

          new_BMI  new_high_Age  new_high_BMI  Sitenum  
MomID                                                   
41-00003       22             1             1       41  
41-00004       31             1             1       41  
41-00006       22             1             1       41  
41-00007       24             2             1       41  
41-00008       18             1             0       41  
...           ...           ...           ...      ...  
52-07247       38             0             1       52  
52-07248       24             1             1       52  
52-07249       23             1             1       52  
52-07250       23             0             1       52  
52-07251       29             2             1       52  

[136487 rows x 196 columns]

In [22]:
df['Delmode'].value_counts()

1    85364
4    25818
5    15989
2     6019
3     3297
Name: Delmode, dtype: int64

In [60]:
chiData = df[['high_EBL', 'new_high_Age', 'new_high_BMI', 'Delmode', 'HxnumCS', 'CPD', 'Hyp_ace']].copy()
chiData 

high_EBL  new_high_Age  new_high_BMI  Delmode  HxnumCS  CPD  Hyp_ace
MomID                                                                         
41-00003         0             1             1        1        0    0        0
41-00004         0             1             1        1        0    0        0
41-00006         0             1             1        1        0    0        0
41-00007         0             2             1        4        0    0        0
41-00008         0             1             0        1        0    0        0
...            ...           ...           ...      ...      ...  ...      ...
52-07247         0             0             1        2        0    0        0
52-07248         0             1             1        3        1    0        0
52-07249         1             1             1        5        1    0        0
52-07250         0             0             1        1        0    0        0
52-07251         0             2             1        1        0    0        0

[136487 rows x 7 columns]

In [61]:
# Delmode as binary
chiData.loc[(chiData['Delmode'] < 4), 'Delmode'] = 0
chiData.loc[(chiData['Delmode'] >= 4), 'Delmode'] = 1
chiData

high_EBL  new_high_Age  new_high_BMI  Delmode  HxnumCS  CPD  Hyp_ace
MomID                                                                         
41-00003         0             1             1        0        0    0        0
41-00004         0             1             1        0        0    0        0
41-00006         0             1             1        0        0    0        0
41-00007         0             2             1        1        0    0        0
41-00008         0             1             0        0        0    0        0
...            ...           ...           ...      ...      ...  ...      ...
52-07247         0             0             1        0        0    0        0
52-07248         0             1             1        0        1    0        0
52-07249         1             1             1        1        1    0        0
52-07250         0             0             1        0        0    0        0
52-07251         0             2             1        0        0    0        0

[136487 rows x 7 columns]

In [62]:
X = chiData.drop('high_EBL', axis=1)
y = chiData['high_EBL']
X.shape, y.shape

((136487, 6), (136487,))

In [63]:
from sklearn.feature_selection import chi2
np.set_printoptions(precision=2, suppress=True)
chi_vals, p_vals = chi2(X, y)
chi_vals

array([  20.93,   72.23, 7289.17, 1439.96,    3.64,    0.66])

In [64]:
# Before making Delmode binary (1-5)
#from sklearn.feature_selection import chi2
#chi_vals, p_vals = chi2(X, y)
#chi_vals

# Results (new_high_Age, new_high_BMI, Delmode)
#array([   20.93119155,    72.23475626, 10918.24418593])
#array([4.76079165e-06, 1.91060887e-17, 0.00000000e+00]) <- pvalues

### I think something is wrong. CPD has a Cramer value of 0.00098 so shouldn't have a p-value of 0.056. This is basically saying that almost all of our variables are dependent.

In [67]:
np.set_printoptions(precision=4, suppress=True)
p_vals

array([0.    , 0.    , 0.    , 0.    , 0.0562, 0.4162])

In [66]:
chi2(chiData[['CPD']], y)

(array([3.645]), array([0.0562]))